
package appPack;

import static appPack.mainFrame.dtm;
import static appPack.mainFrame.dtmo;
import static appPack.mainFrame.id;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

public class newOrder extends javax.swing.JFrame {
    
    
    
    public mainFrame MF;
    DB db = new DB();
    //static String oid = "";
    static String oName = "";
    static String oSurname = "";
    static String status = "";
    static String oAddress = "";
    static String amount = "";
        
    
    public newOrder(mainFrame _MF) {
        MF = _MF;
        initComponents();
        orderDisplay();
        txtoName.setText(MF.name);
        txtoSurname.setText(MF.surname);
        txtoAddress.setText(MF.address);
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtoName = new javax.swing.JTextField();
        txtoSurname = new javax.swing.JTextField();
        txtoAddress = new javax.swing.JTextField();
        txtoAmount = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnCreateOrder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Name");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Surname");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Address");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Amount");

        btnCreateOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/ok_button.png"))); // NOI18N
        btnCreateOrder.setText("Create New Order");
        btnCreateOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(btnCreateOrder, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtoName)
                            .addComponent(txtoSurname)
                            .addComponent(txtoAddress)
                            .addComponent(txtoAmount)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtoName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtoSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtoAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtoAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(33, 33, 33)
                .addComponent(btnCreateOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateOrderActionPerformed
        oName = txtoName.getText();
        oSurname = txtoSurname.getText();
        status = "Preparing";
        oAddress = txtoAddress.getText();
        amount = txtoAmount.getText();
        
        try {
         // ekleme işlemi başarılı ise 0 dan büyük bir değer
        //0 dan küçük bir değer ise ekleme işlemi başarısız
       int orderSave = db.baglan().executeUpdate("INSERT INTO `orders` (`oid`, `oName`, `oSurname`, `oStatus`, `oAddress`, `oCost`,`oDate`) "
               + "VALUES (NULL, '"+oName+"', '"+oSurname+"', '"+status+"', '"+oAddress+"', '"+amount+"', now());");
       
        if(orderSave>0)
        {
            JOptionPane.showMessageDialog(rootPane, "New order operation is successful!");
            dtmo.addRow(new String[]{null, oName, oSurname, status, oAddress, amount });
            orderDisplay();
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "New order operation is unsuccessful!");  
        }
        } 
        catch (Exception e) 
        {
            System.err.println("Order Creation Error!"+e);
        }

        
    }//GEN-LAST:event_btnCreateOrderActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        MF.jTable2.setModel(dtmo); 
        
        dispose();
        
    }//GEN-LAST:event_formWindowClosed

    public void orderDisplay()
    {
        String oid = "";
        try 
        {
            while(dtmo.getRowCount() > 0)
            {
                dtmo.removeRow(0);
            }
            
            String query = "SELECT * FROM `orders`";    
            ResultSet rs = db.baglan().executeQuery(query);
            while(rs.next())
            {
                oid = rs.getString("oid");
                oName = rs.getString("oName");
                oSurname = rs.getString("oSurname");
                status = rs.getString("oStatus");
                oAddress = rs.getString("oAddress");
                amount = rs.getString("oCost");
                
                dtmo.addRow(new String[]{oid, oName, oSurname, status, oAddress, amount}); 
            }
                MF.jTable2.setModel(dtmo); 
        } 
        catch (Exception e) 
        {
            System.err.println("New order error"+e);
        }
    } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        /*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newOrder().setVisible(true);
            }
        }); */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCreateOrder;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JTextField txtoAddress;
    public javax.swing.JTextField txtoAmount;
    public javax.swing.JTextField txtoName;
    public javax.swing.JTextField txtoSurname;
    // End of variables declaration//GEN-END:variables
}
